const TOKENLEN = 48;
const REFERERCODELEN = 10;

const B_ASSIGN_DELINQUENT_ITEMS = true;
const B_ALLOW_TO_ASSIGN_MULTIPLE_ITEMS_PER_USER = true;
module.exports = {
  TOKENLEN,
  REFERERCODELEN,
  B_ASSIGN_DELINQUENT_ITEMS,
  B_ALLOW_TO_ASSIGN_MULTIPLE_ITEMS_PER_USER,
};
